[package]
name = "playcurrent/shards"
description = "Put Roblox players into defined regions to optimize matchmaking latency."
license = "MPL-2.0"

authors = ["lewisakura <lewi@lewisakura.moe>"]

version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"

realm = "shared"
